/**
 * Demo cohort data — 50 Week 1 PM-tool submissions. Dates May 11–15, 2026.
 * ~15 competeForWin, remainder false.
 *
 * - description: one-line product summary (all rows).
 * - pitch: competing-only “why we should win” sentence; null when not competing.
 */

const MAY_DATES = [
  "2026-05-11",
  "2026-05-12",
  "2026-05-13",
  "2026-05-14",
  "2026-05-15",
];

const PROJECT_ROWS = [
  ["Sprintline", "Kanban and WIP limits tuned for how your team actually ships each week."],
  ["Pulseboard", "Async standups in a single feed so status never lives only in meeting notes."],
  ["Handoff Map", "Milestone owners and dependencies on one lane so handoffs do not stall work."],
  ["Benchmark", "Capacity and PTO in one view so sprint commitments match who is really here."],
  ["Inbox PM", "Turn Slack asks into triaged backlog items with lightweight acceptance checks."],
  ["Retroflow", "Retro themes become follow-up tasks with owners and due dates automatically."],
  ["Program Lens", "Multi-project roll-up for execs: health, risk, and next milestones at a glance."],
  ["Cohort Rail", "Ceremonies, docs, and decisions in one rail so the team has a single home base."],
  ["Lanekeeper", "Swimlanes per initiative with WIP caps so parallel work stays under control."],
  ["Northstar OKR", "Goals linked to epics and PRs so progress is visible without another sheet."],
  ["Blockparty", "Flag blockers with severity and blast radius so leads can reprioritize fast."],
  ["Scopeguard", "Change requests get impact notes before scope shifts land in the sprint."],
  ["Shipsheet", "Release checklist templates that gate deploys without a heavyweight tool."],
  ["Deskday", "Desk booking tied to on-site ceremonies for hybrid squads."],
  ["Ritualist", "Recurring ceremonies on autopilot with agendas and rotating facilitators."],
  ["Ganttlight", "Lightweight timelines when you need dates without enterprise Gantt noise."],
  ["Pairboard", "Pairing rotations and focus blocks for teams that mob and pair weekly."],
  ["Debtledger", "Tech debt tickets tied to business outcomes so paydown wins budget."],
  ["Riskradar", "Risks with likelihood, impact, and mitigation owners on a simple matrix."],
  ["Stakeholdr", "Read-only views for stakeholders with curated metrics and narrative."],
  ["Docdelta", "What changed in specs this week, summarized for eng and PM in one digest."],
  ["SLOside", "Error budgets and on-call context next to the roadmap so tradeoffs stay honest."],
  ["Triagekit", "Bug intake rules that route by area, severity, and on-call without inbox chaos."],
  ["Cadence", "Team heartbeat metrics: throughput, cycle time, and carry-over in one chart."],
  ["Briefcase", "Weekly brief generator from tickets and commits for leadership updates."],
  ["Aligner", "Problem statements and success metrics pinned to every epic for alignment."],
  ["Icebox PM", "Ideas parking lot with gentle aging so the backlog stays intentional."],
  ["Playbook PM", "Runbooks for launches: owners, comms, and rollback in one checklist."],
  ["Huddlelog", "Notes from ad-huddles linked to tickets so decisions are traceable."],
  ["Mosaic", "Cross-team initiatives as tiles with status colors for portfolio reviews."],
  ["Quorum", "Decision log with who was consulted and what was chosen—no silent rewrites."],
  ["Spanplan", "Multi-week plans with buffers so optimistic dates do not hide slack."],
  ["Threadbase", "Email threads summarized into action items with PM assignment."],
  ["Vaultline", "Sensitive project docs with access trails for compliance-minded teams."],
  ["Kickoffkit", "Kickoff agendas, RACI, and risks generated from a short questionnaire."],
  ["Aftermath", "Post-incident timelines with customer impact and follow-up tasks tracked."],
  ["Orbit", "Customer commitments mapped to internal milestones for CS and PM alignment."],
  ["Patchwork", "Dependency map across vendors and internal teams for platform programs."],
  ["Signalroom", "Executive signals: burn, scope change, and staffing in a calm weekly page."],
  ["Backloger", "Backlog hygiene scores: stale items, missing estimates, and duplicates."],
  ["Sprintdoc", "Living sprint doc that pulls in velocity, goals, and risks automatically."],
  ["Outcometrack", "Outcome hypotheses per initiative with learnings captured at milestones."],
  ["Crewcall", "On-call and project staffing overlay so you know who is stretched thin."],
  ["Mentorloop", "PM mentorship pairings with prompts and shared notes for cohort programs."],
  ["Budgetbeam", "Forecast vs actual hours per epic to catch overrun before invoices do."],
  ["Specsheet", "PRD sections versioned with diffs so scope debates reference concrete text."],
  ["Rollcall", "Attendance and participation in ceremonies for distributed accountability."],
  ["Pinpoint", "Root-cause prompts for slipped dates without blamey retro templates."],
  ["Glassroom", "Transparent priorities board for internal teams with rationale snippets."],
  ["Harbor", "Safe harbor sprint: reserved capacity for support and unplanned work."],
];

const FIRST_NAMES = [
  "Marcus",
  "Priya",
  "Jordan",
  "Elena",
  "Sam",
  "Aisha",
  "Noah",
  "Riley",
  "Diego",
  "Mei",
  "Omar",
  "Hannah",
  "Viktor",
  "Amara",
  "Lucas",
  "Zoe",
  "Kenji",
  "Fatima",
  "Bridget",
  "Theo",
  "Nina",
  "Andre",
  "Sofia",
  "Malik",
  "Grace",
  "Ethan",
  "Yuki",
  "Camila",
  "James",
  "Leah",
  "Daniel",
  "Iris",
  "Paul",
  "Tessa",
  "Ryan",
  "Anika",
  "Chris",
  "Morgan",
  "Alex",
  "Quinn",
  "Taylor",
  "Jamal",
  "Renee",
  "Blake",
  "Casey",
  "Devon",
  "Jordan",
  "Skyler",
  "Rowan",
  "Avery",
];

const LAST_NAMES = [
  "Chen",
  "Sharma",
  "Okonkwo",
  "Vasquez",
  "Whitaker",
  "Mensah",
  "Bergstrom",
  "Nakamura",
  "Flores",
  "Lin",
  "Haddad",
  "Kerr",
  "Petrov",
  "Diallo",
  "Reyes",
  "Park",
  "Tanaka",
  "Hassan",
  "O’Neill",
  "Marin",
  "Patel",
  "Ruiz",
  "Nguyen",
  "Brooks",
  "Kim",
  "Foster",
  "Sato",
  "Romero",
  "Okafor",
  "Singh",
  "Walsh",
  "Abbott",
  "Morales",
  "Chung",
  "Ellis",
  "Bakshi",
  "Hart",
  "Lopez",
  "Ibrahim",
  "Cole",
  "Ng",
  "Ford",
  "Martinez",
  "Yates",
  "Pratt",
  "Sullivan",
  "Diaz",
  "Cho",
  "Bennett",
  "Hayes",
];

/** One-sentence “why we should win” for the 15 competing entries (indices 0–14). */
const COMPETING_WIN_PITCHES = [
  "We should win because Sprintline is the first tool that ties WIP limits directly to daily standups—teams finally see blockers before the sprint slips, not after.",
  "Pulseboard deserves the win: it kills redundant status meetings by making async updates the source of truth, which is how modern distributed PM actually works.",
  "Handoff Map should win—ownership gaps between teams are where programs die, and we make every handoff explicit with dates and names in one shared lane.",
  "Benchmark should win because capacity lies are the silent killer of sprint commitments; we show who is really available before the plan is promised to leadership.",
  "Inbox PM should win—Slack is where work starts, and we are the only pitch that turns thread noise into triaged backlog without forcing a new habit for ICs.",
  "Retroflow should win: retros that do not ship follow-ups are theater; we close the loop automatically so every theme becomes an owned task with a due date.",
  "Program Lens should win because execs need one honest roll-up across projects—health, risk, and next milestones—without another slide deck factory.",
  "Cohort Rail should win: hybrid cohorts fracture across calendars, docs, and chat; one rail for ceremonies and decisions is the glue this format has been missing.",
  "Lanekeeper should win—parallel initiatives without WIP discipline burn teams out; swimlanes with caps keep focus where strategy says it should be.",
  "Northstar OKR should win because OKRs fail when they float above the work; we bind goals to epics and PRs so progress is provable, not narrated.",
  "Blockparty should win: not all blockers are equal, and we are the only tool that ranks blast radius so leads reprioritize the fires that actually threaten ship dates.",
  "Scopeguard should win—late scope changes derail sprints when impact is vague; we force a lightweight impact note before a shift lands in the plan.",
  "Shipsheet should win: releases still break on forgotten steps; our checklists gate deploys without importing an enterprise release manager nobody will adopt.",
  "Deskday should win because hybrid ceremonies fail when nobody knows who is on-site; we tie desk booking to the actual cadence of the team’s week.",
  "Ritualist should win—recurring ceremonies rot when prep is uneven; we automate agendas and rotating facilitators so every ritual stays sharp without nagging.",
];

function slugify(name) {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
}

function buildSubmissions() {
  return PROJECT_ROWS.map(([projectName, description], i) => {
    const id = `s${i + 1}`;
    const slug = slugify(projectName);
    const competeForWin = i < 15;
    return {
      id,
      builderName: `${FIRST_NAMES[i]} ${LAST_NAMES[i]}`,
      photo: `https://picsum.photos/seed/jackie-w1-${id}/200/200`,
      description,
      pitch: competeForWin ? COMPETING_WIN_PITCHES[i] : null,
      projectName,
      loomUrl: `https://www.loom.com/share/placeholder-${slug}`,
      liveUrl: `https://${slug}-demo.example.com`,
      repoUrl: `https://github.com/cohort-demo/${slug}`,
      week: 1,
      submissionDate: MAY_DATES[i % MAY_DATES.length],
      competeForWin,
    };
  });
}

export const submissions = buildSubmissions();
