/** @type {Record<number, string>} */
export const WEEK_DELIVERABLES = {
  1: "Everyone builds a PM tool. The cohort picks a winner on Friday; the winner runs the cohort PM tool for the rest of the program.",
  2: "Everyone builds a comms platform for the cohort. Same vote-and-pick-a-winner format. Winner runs comms for the rest of the cohort.",
  3: "Everyone builds a marketing platform that does outbound, not just inbound -- gets the cohort's work into the public eye AND handles the replies that come back. Same vote format; winner maintains it. Note: Mon May 26 is Memorial Day and Tue May 27 is the in-person immersion event at Hult. Plan your build time around both.",
  4: "Everyone ships an education tool that gets merged into Ludwitt. As users consume credits via your tool, you earn a revenue share -- every shipped tool earns its author fees in perpetuity. No vote, no presentations. Every shipped + merged tool counts. Submission target = Ludwitt. You open a PR against the Ludwitt repo (not this one). Mergeability is the acceptance criterion. Submission mechanics TBD at the Mon Jun 1 kickoff.",
  5: "Build whatever YOU want. Your own startup project. No vote. No template. No PR to this repo. The cohort tools (PM, comms, marketing) are still running -- use them to ship faster. Friday show-and-tell at Fri Jun 12, 6pm EST. Each person gets ~3 minutes. No formal pitch -- just 'here's what I built and what I'm doing next.' Optional. What 'good' looks like: end the week with something you can show -- a working prototype, a landing page with real signups, a public alpha. The bar is 'I shipped something I'm proud of,' not 'I won a vote.'",
  6: "Pick a major open-source project and land a merged PR upstream. Friday is also demo day with hiring partners -- bring your merged PR URL. Pick something with real distribution -- a popular framework, dev tool, or library. Not your own side project. A doc fix counts if it's a real one. A feature counts. Anything 'good first issue' counts. Bar is the upstream maintainer hits Merge. Bring the merged-PR URL to demo day -- that's the submission. No JSON file, no PR to this repo. Just the upstream PR link, ready to share.",
};
